### ISSUE TITLE
[Bug] 使用kaggle平台部屬方式，用RPGMaker_LLM_Translator進行翻譯會卡死

### ISSUE THREAD

**Issue by getoutnow2013** [SakuraLLM/SakuraLLM#104]
**描述一下Bug**
使用kaggle平台部屬方式，也就是本wiki中，第三種部屬方式，部屬完之後可以進入llama的畫面
使用RPGMaker_LLM_Translator進行翻譯，大約進行250~350次左右的翻譯
整個kaggle虛擬機就會無法再進行翻譯，不接受任何API呼叫

**复现步骤**
1.先啟動kaggle平台的部屬方式
llama.cpp版本: b2859
更新时间： 2024/06/05
REPO = "SakuraLLM/Sakura-14B-Qwen2beta-v0.9.2-GGUF"
MODEL = "sakura-14b-qwen2beta-v0.9.2-iq4xs.gguf"
2.無論是採用save and run all，或分兩階段來執行腳本，結果均相同。
3.從kaggle平台啟動完成後，會有第一個 all slots are idle，此時可以進入llama.cpp的設定畫面

4.透過RPGMaker_LLM_Translator 的 main_dev.py (目前最新為0.3.5_fix 版本) 進行翻譯
5.main_dev.py 每次呼叫API翻譯時，都會有 request -> slot is processing task -> slot released -> all slots are idle 的循環
6.約250~350次左右的API呼叫後，就會卡死，會停在 request 狀態。
7.main_dev.py的視窗會停滯超久之後，收到 Max retries exceeded with url: /v1/chat/completions (Caused by SSLError 的訊息
8.之後的發送會重複6的狀態，kaggle這邊不會顯示有新的 request 進來，且llama.cpp設定畫面也無法進入了

**预期结果**
如上描述的階段 6 ~ 8，kaggle的虛擬機階段將無法繼續使用
必須整個關閉，重新啟動新的虛擬機，從階段 1 重新開始，然後一樣到階段 6 ~ 8 又會死掉

**截图**
1. Kaggle 平台部屬腳本的內容（除了ngrok的token遮住，其他均未修改）
![20240810_SAK_001](https://github.com/user-attachments/assets/87340544-1951-48a3-8369-bfaecab90349)

2. 上面為正常的API 呼叫循環(request -> slot is processing task -> slot released -> all slots are idle)
但最後卡死時，停在 request，無任何後續動作
![20240810_SAK_002](https://github.com/user-attachments/assets/80a09a61-2284-4129-86ea-aa33d357219e)

3. main_dev.py 這邊的視窗停滯很久後，會出現 Max retries exceeded with url 訊息
![20240810_SAK_003](https://github.com/user-attachments/assets/18a54ca1-f7fa-463e-87a3-cd048ed8d389)

**版本与参数（重要）**
 - OS：Windows 10
 - Python版本：3.12.3
 - 是否使用GPU：Kaggle T4x2
 - 你使用的llama.cpp/llama-cpp-python/autogptq/transformers库的版本：llama.cpp b2859
 - 你使用的模型版本：sakura-14b-qwen2beta-v0.9.2-iq4xs.gguf
 - 如果是模型输出问题，请同时附上模型的解码参数：無修改任何預設參數。

**其他信息**
之前我用 kaggle+**TGW**+sakura-13b-lnovel-v0.9b-Q8_0.gguf 進行翻譯
使用 main_dev.py 呼叫，可以進行 10000 次以上的API呼叫（超過8小時），都不會中斷。

只是必須修改 main_dev.py 的呼叫方式，從：
![20240810_SAK_004](https://github.com/user-attachments/assets/22610771-4ecc-41b4-bdb3-c2aea8b00705)

改成：
![20240810_SAK_005](https://github.com/user-attachments/assets/f2ac60db-9897-426c-9857-3a160374264e)

**Comment by kurikomoe** [comment]
看起来像是 ngrok 隧道炸了。kaggle 上的 llama.cpp 没问题

**Comment by getoutnow2013** [comment]
> 看起来像是 ngrok 隧道炸了。kaggle 上的 llama.cpp 没问题

ngrok tunnel 會爆掉是很奇怪的情況
用wiki中的部屬方式，每次翻譯個250-350次就會爆掉

剛剛，我重新用 ngrok+kaggle+tgw 的方式來跑
模型採用：
SakuraLLM/Sakura-14B-Qwen2beta-v0.9.2-GGUF
sakura-14b-qwen2beta-v0.9.2-q6k.gguf

同一隻 main_dev.py 已經跑超過40分鐘了（當然messages那塊要照我上面說明的，拔掉 role:system 的部份）
至少1000次以上翻譯，都沒問題（照之前狀況，10000次以上也沒問題）

kaggle+TGW+sakura-14b-qwen2beta-v0.9.2-q6k.gguf
![20240810_TGW_001](https://github.com/user-attachments/assets/d0f915bf-9d44-40c4-b64d-e38f6068d385)

load model: sakura-14b-qwen2beta-v0.9.2-q6k.gguf
![20240810_TGW_002](https://github.com/user-attachments/assets/b5afc692-6ad2-4bee-9b3a-952834730988)

main_dev.py 目前已執行超過1000次 request 了
![20240810_TGW_003](https://github.com/user-attachments/assets/504dd315-8613-43a1-986c-419e2970166f)

**Comment by cycham0** [comment]
不止，現在kaggle那邊封了saukuraLLM了，我之前才有帳因為這樣封了。
Thank you for your inquiry. We have unblocked your "{id}" Kaggle account. The account was locked as there was **SakuraLLM** used in your account. Please avoid SakuraLLM on Kaggle platform as it is prohibited on Kaggle platform. This will lead to permanent ban. The account will not be reinstated if the account gets blocked again.

**Comment by kurikomoe** [comment]
Since Kaggle is banning the SakuraLLM, this issue will be closed.
