### ISSUE TITLE
[Question] What's the Sakura backend API endpoint (for Luna Translator)

### ISSUE THREAD

**Issue by Farooq87** [SakuraLLM/SakuraLLM#105]
What link to add there in order Sakura works.
![sakuraint](https://github.com/user-attachments/assets/9b22e800-71cf-44d0-98a4-c497add7aa79)

**Comment by kurikomoe** [comment]
by default, it should be `http://127.0.0.1:5000/v1/chat/completions`, but it depends on the frontend software you used and the startup parameters you used.

**Comment by Farooq87** [comment]
> by default, it should be `http://127.0.0.1:5000/v1/chat/completions`, but it depends on the frontend software you used and the startup parameters you used.

Do you mean that I need to install some other software aside of Luna?

**Comment by kurikomoe** [comment]
Oh, you are using LunaTranslator, then you should prepare 3 things: 
1. Luna translator itself.
2. Sakura model file (e.g [sakura-14b-qwen2beta-v0.9.2-iq4xs.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2beta-v0.9.2-GGUF/blob/main/sakura-14b-qwen2beta-v0.9.2-iq4xs.gguf))
3. a model file loader such as `llama.cpp` (recommend for beginners) or `this repo`, which loads the Sakrua model and provides translation service via HTTP API.

If any questions, please refer to this tutorial which uses SakuraModel to provide service for light novel translations:
https://books1.fishhawk.top/forum/656d60530286f15e3384fcf8

**Comment by Farooq87** [comment]
> Oh, you are using LunaTranslator, then you should prepare 3 things:
> 
> 1. Luna translator itself.
> 2. Sakura model file (e.g [sakura-14b-qwen2beta-v0.9.2-iq4xs.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2beta-v0.9.2-GGUF/blob/main/sakura-14b-qwen2beta-v0.9.2-iq4xs.gguf))
> 3. a model file loader such as `llama.cpp` (recommend for beginners) or `this repo`, which loads the Sakrua model and provides translation service via HTTP API.
> 
> If any questions, please refer to this tutorial which uses SakuraModel to provide service for light novel translations: https://books1.fishhawk.top/forum/656d60530286f15e3384fcf8

Thank you!

**Comment by kurikomoe** [comment]
By the way, I have seen that you are using Russian as the main OS language in the picture. Please remember that SakuraLLM only provides Japanese to Chinese translation
