### ISSUE TITLE
[Bug] sakura-32b-qwen2beta-v0.9-iq4xs在某段翻译中出现的单行退化问题

### ISSUE THREAD

**Issue by bennylii** [SakuraLLM/SakuraLLM#106]
**描述一下Bug**
清晰简明地描述你遇到的Bug
[1049] syosetu/n4147dw/1050 
　分段1/8 
　　第1次　行数不匹配  [详细] 
　　第2次　行数不匹配  [详细] 
　　逐行翻译 
　分段2/8 
　　第1次　行数不匹配  [详细] 
　　第2次　成功  [详细] 
　分段3/8 
　　第1次　成功  [详细] 
　分段4/8 
　　第1次　退化  [详细] 
　　第2次　退化  [详细] 
　　逐行翻译 
　　单行退化1次  [详细] 
　　单行退化2次  [详细] 
发生错误，跳过：Error: 单个分段有2行退化，Sakura翻译器可能存在异常

**断点**
日志详情 - 第1次　成功

　できているんだよ。
　結晶化して、氷の花のようになった、
　精霊花を、ひとつ、
　そんな気持ちをこめて、
　小さな魔女の、目の前に出した。
　・・・パキ、キ。
「……くれるです？」
『『『　クルル　』』』
「きれいです……♪」
　言いたいことは、伝わらなかったけど、
　元気には、なったみたいだ。
　その時、ボクと同じく、
　大きくなった うさ丸が、
　隣へ、足から炎を噴きながら、
　ピタっ、と、止まった。
『『『　にょきっと……　』』』
　どうだった？
｟｟｟　パンチを、いれてきた　｠｠｠
　みてたよ。
｟｟｟　でも、あのウネウネ、固い……　｠｠｠
　うん……。
　すまない。
　ボク、手伝えなくて。
｟｟｟　……！　いや、
　　　　その子を乗せてくれてて、
　　　　助かる！
　　　　おかげで自由に動けるし、
　　　　ボクは、丸くて、
　　　　乗りにくいから♪　｠｠｠
　耳の間に乗せれば、
　そうでもないと、思うよ？
『『『　にょきっと・・・♪
　　　　にょっき・・・！！　』』』
　やっぱり、炎は、ダメ？
｟｟｟　うん……直前で、
　　　　クネッと、曲がるんだ　｠｠｠
　困ったね。
｟｟｟　こまった……。
　　　　ずっと、マッテ、マッテ、

　已经完成了哦。
　结晶化，变成冰花的，
　精灵花，一朵，
　带着这样的心情，
　在小小魔女的面前出现。
　・・・啪叽，叽。
「……要给我吗？」
『『『　库露露　』』』
「好漂亮……♪」
虽然想说的话，没有传达给她，
不过，她好像打起精神了。
这个时候，和我一样，
变大的兔丸，
从脚喷出火焰，来到我身边，
啪哒，停了下来。
『『『　扭扭……　』』』
怎么样？
『『『　我用拳头，打过去了　』』』
我看到了哦。
『『『　可是，那个扭来扭去的，好硬……　』』』
嗯……
抱歉。
我，没办法帮忙。
『『『　……！不，
　　　　你让那孩子坐上来，
　　　　帮了大忙！
　　　　托你的福，能够自由行动，
　　　　我，圆圆的，
　　　　不好坐♪　』』』
只要坐在耳朵之间，
我觉得，不会不好坐哦？
『『『　扭扭……♪
　　　　扭……！！　』』』
果然，火焰，不行？
『『『　嗯……在前面，
　　　　会扭来扭去　』』』
伤脑筋呢。
『『『　伤脑筋……
　　　　一直，停，停，

日志详情 - 第1次　退化

　　　　って、言ってる。
　　　　正直、こわい　｠｠｠
　あれが……。
　怖くないヤツなんて、
　いないよ。
｟｟｟　珍しく……弱気だね？　｠｠｠
　ボクだって、繊細なんだよ？
『『『　にょきにょき♪　』』』
　あ、笑ったなー。
｟｟｟　ごめん、ごめん。
　　　　よし、もういっかい、
　　　　いってくるよ　｠｠｠
　うん、やっつけてやんなよ！
｟｟｟　……！　本当は、
　　　　アイツも、悪いワケじゃ、
　　　　ないんだ　｠｠｠
　え？
｟｟｟　アイツは……好きなモノを、
　　　　食べようと、している、
　　　　だけじゃないか　｠｠｠
『『『　……クルル　』』』
｟｟｟　ボクにとっての、
　　　　リンゴや、ニンジンが……、
　　　　アイツにとっては、
　　　　その子、、、だった　｠｠｠
　……。
｟｟｟　だから、これは、
　　　　正義じゃない　｠｠｠
『『『　クル？　』』』
｟｟｟　わがままを、貫く、戦いだ　｠｠｠
　……ふふ、そうだね。
　彼女が──、
『『『　……にょき？　』』』
　首領・アンティが、
　言いそうだ♪
『『『　……にょきっと♪♪♪　』』』　
　大きな、おおきな、うさ丸は。
　空中でホバー飛行しながら、
　赤い装甲で覆われた、

　　　　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕

日志详情 - 第2次　退化

　　　　って、言ってる。
　　　　正直、こわい　｠｠｠
　あれが……。
　怖くないヤツなんて、
　いないよ。
｟｟｟　珍しく……弱気だね？　｠｠｠
　ボクだって、繊細なんだよ？
『『『　にょきにょき♪　』』』
　あ、笑ったなー。
｟｟｟　ごめん、ごめん。
　　　　よし、もういっかい、
　　　　いってくるよ　｠｠｠
　うん、やっつけてやんなよ！
｟｟｟　……！　本当は、
　　　　アイツも、悪いワケじゃ、
　　　　ないんだ　｠｠｠
　え？
｟｟｟　アイツは……好きなモノを、
　　　　食べようと、している、
　　　　だけじゃないか　｠｠｠
『『『　……クルル　』』』
｟｟｟　ボクにとっての、
　　　　リンゴや、ニンジンが……、
　　　　アイツにとっては、
　　　　その子、、、だった　｠｠｠
　……。
｟｟｟　だから、これは、
　　　　正義じゃない　｠｠｠
『『『　クル？　』』』
｟｟｟　わがままを、貫く、戦いだ　｠｠｠
　……ふふ、そうだね。
　彼女が──、
『『『　……にょき？　』』』
　首領・アンティが、
　言いそうだ♪
『『『　……にょきっと♪♪♪　』』』　
　大きな、おおきな、うさ丸は。
　空中でホバー飛行しながら、
　赤い装甲で覆われた、

　　　　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕。　”
“““　它这么说。
　　　　老实说，很可怕

日志详情 - 单行退化1次

　　　　正直、こわい　｠｠｠

　　　　老实说，我很害怕　

日志详情 - 单行退化2次

　　　　いってくるよ　｠｠｠

　　　　我出发了　

**复现步骤**
如何复现你遇到的Bug

**预期结果**
清晰简明地描述你预期的结果

**截图**
可以添加截图以提供更完整的信息

**版本与参数（重要）**
 - OS: [e.g. Windows] linux
 - Python版本 [e.g. 3.10]llama.cpp
 - 是否使用GPU，使用什么GPU. autoDL上的vGPU32g，nvidia-smi报4080 32g？问客服也谜语人。
 - 你使用的llama.cpp/llama-cpp-python/autogptq/transformers库的版本 [e.g. llama.cpp b1604 cu117] 你得问fishhawk佬，readme.md里面我没找到版本号，用的是 https://www.codewithgpu.com/i/FishHawk/auto-novel/Sakura-LNovel 的0.9.4版本
 - 你使用的模型版本 [e.g. Sakura-13B-LNovel-v0.9.0pre3-Q5_K_M.gguf] sakura-32b-qwen2beta-v0.9-iq4xs
 - 如果是模型输出问题，请同时附上模型的解码参数 [e.g. temperature: 0.1, top_p:0.3, frequency_penalty: 0.0] run里面填的只有 llama.cpp/llama-server -m ${MODEL}.gguf -c 4096 -ngl 999 -a ${MODEL} --port 6006 ，不清楚参数

**其他信息**
关于你遇到的Bug的更多信息
可以自己试着翻译一下

**Comment by bennylii** [comment]
其实这本书挺容易遇到这类问题的：

日志详情 - 第1次　退化

　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❜❛❜❛❜　　❜❛❜❛❜❛❜❛❜❛❜❛❛
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❛❜❛❜❛　　❜❛❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛　　　　　　　　❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛　　　　　　　　❛❜❛❜❛❜❛❜❛❜❛
　　　❛❜❛❜❛❜❛❜❛　　　　　　　　❛❜❛❜❛❜❛❜❛❜❛
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　　　　　❛❜❛❜❛❜❛❜❛❜❛❜❛
　　　❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛
　　　❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛
白童：「──"射撃"……しているのか？」
妹乳：「・・・っ！！！」
花狼：『『『　クルルぅう！！！　』』』
　ユユユが、ポツリと言い、
　後ろに乗るヒキハは、
　よく、勇者のカタチを、見る。
妹乳：「あの、うで、は・・・！！」
　うさ丸の右手が、、、
　──また、" 衝撃波 "を、放つ！！
炎兎：『『『　──にょきっと、
　　　　　　　なああああああっっ！！！　』』』
　──ックゥ──ォキュ──オオオオオンンン──！！！

　　　❜❜❜❜❜❜❜❜❜❜❜　　❜❜❜❜❜　　❜❜❜❜❜❜❜❜❜❜❜❜
　　　❜❜❜❜❜❜❜❜❜❜❜　　❜❜❜❜❜　　❜❜❜❜❜❜❜❜❜❜❜❜
　　　❜❜❜❜❜❜❜❜❜　　❜❜❜❜❜　　❜❜❜❜❜❜❜❜❜❜
　　　❜❜❜❜❜❜❜❜❜　　❜❜❜❜❜❜❜❜❜❜
　　　❜❜❜❜❜❜❜❜❜　　❜❜❜❜❜❜❜❜❜❜
　　　❜❜❜❜❜❜❜❜❜❜❜　　❜❜❜❜❜❜❜❜❜❜❜❜
　　　❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜❜
　　　❜❜栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀栀


日志详情 - 第1次　退化

　　　　　　　　　　　　　　　　　❜
闇兎：❛❜　　❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜　　　❜
　　　　　❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❜❛❜❛❜　　❛❜❛❜❛❜❛❜❛　❜
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❜❛❜❛❜　　❜❛❜❛❜❛❜❛❜❛❜❛❛
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❛❜❛❜❛　　❜❛❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛　　　　　+　　、❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛　　　◢◣　、　❛❜❛❜❛❜❛❜❛❜❛
　　　❛❜❛❜❛❜❛❜❛　　、◥◤　　　❛❜❛❜❛❜❛❜❛❜❛
　　　　❛❜❛❜❛❜❛❜、　+　　｀　❛❜❛❜❛❜❛❜❛❜❛❜❛❛❜
　　　　　　❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜　❛　❜
　　　❛　❜　　　❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜　　　❛❜
　　　　❜　　　　　　　　　　❛
　　　　　　　　　　　　　　　　❛
　　　　　　　　　　　　　　　❜
白童：「　──── " 弱点 " だ。　　」

………………………………………………………………………………………………
暗兔：「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「「



日志详情 - 第2次　退化

　　　　　　　　　　　　　　　　　❜
闇兎：❛❜　　❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜　　　❜
　　　　　❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❜❛❜❛❜　　❛❜❛❜❛❜❛❜❛　❜
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❜❛❜❛❜　　❜❛❜❛❜❛❜❛❜❛❜❛❛
　　　❛❜❛❜❛❜❛❜❛❜❛❜　　❛❜❛❜❛　　❜❛❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛　　　　　+　　、❜❛❜❛❜❛❜❛❜❛❜
　　　❛❜❛❜❛❜❛❜❛　　　◢◣　、　❛❜❛❜❛❜❛❜❛❜❛
　　　❛❜❛❜❛❜❛❜❛　　、◥◤　　　❛❜❛❜❛❜❛❜❛❜❛
　　　　❛❜❛❜❛❜❛❜、　+　　｀　❛❜❛❜❛❜❛❜❛❜❛❜❛❛❜
　　　　　　❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜　❛　❜
　　　❛　❜　　　❛❜❛❜❛❜❛❜❛❜❛❜❛❜❛❜　　　❛❜
　　　　❜　　　　　　　　　　❛
　　　　　　　　　　　　　　　　❛
　　　　　　　　　　　　　　　❜
白童：「　──── " 弱点 " だ。　　」

………………………………………………………………………………………………
暗兔：「「「「「「「「「「「「「「「「「「「「「「「「「「　嘡　」」」」」」」」」」」」」」」」」」」」」」」
………………………………………………………………………………………………
暗兔：「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」
………………………………………………………………………………………………
暗兔：「「「「「「「「「「「「「「「「「「「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」」」」」」」」」」」」」」」」」」
………………………………………………………………………………………………
白兔：「「「「「「「「「「　———— 是 " 弱点 " 。　　」」」」」」」」
………………………………………………………………………………………………
白兔：「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」
………………………………………………………………………………………………
白兔：「「「「「「「「「「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」」」」」」」」
………………………………………………………………………………………………
白兔：「「「「「「「「「「　———— 是 " 弱点 " 。　　」」」」」」」」
………………………………………………………………………………………………
白兔：「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」
………………………………………………………………………………………………
白兔：「「「「「「「「「「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」」」」」」」」
………………………………………………………………………………………………
白兔：「「「「「「「「「「　———— 是 " 弱点 " 。　　」」」」」」」」
………………………………………………………………………………………………
白兔：「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」
………………………………………………………………………………………………
白兔：「「「「「「「「「「嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡嘡　　哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢哢」」」」」」」」
………………………………………………………………………………………………
白兔：「「「「「「「「「「　———— 是 " 弱点 " 。　　」」」」」

**Comment by kurikomoe** [comment]
轻小说机翻站上遇到退化问题的话，请联系站长处理。
