### ISSUE TITLE
[Bug] 按照wiki教程部署并运行后，轻小说机翻机器人不能正确识别模型名称

### ISSUE THREAD

**Issue by damoc451** [SakuraLLM/SakuraLLM#107]
按照wiki上的python部署并运行之后，在轻小说机翻机器人上能够正确输出翻译的内容，但是模型总是被识别为未知
用浏览器开发者模式看了以下猜测是两边获取模型的api没对上，又试了一遍网站提供的打包好的exe能够正确识别模型
基本确定了是api的问题，路由分发接口不一样

**Comment by kurikomoe** [comment]
目前机翻站只能用 llama.cpp

机翻站依赖于 llama.cpp 的特定 api 接口来获取 token 分布数据，用于计算指纹（禁止异常模型提交数据）。
> 并且这个 api 目前不在本 repo 计划范围内。
