### ISSUE TITLE
[Feature Request]请问之后会不会支持多卡推理以及参数量在32B以上的模型？

### ISSUE THREAD

**Issue by Eric20050727** [SakuraLLM/SakuraLLM#110]
比如说使用MLC LLM的张量并行？或者lamma的流水线。

还有就是单块24G显存的卡跑V0.9-32B-iq4已经不会暴显存了，在拥有多卡支持后是否能够训练更大的（比如说72B）的底模？

**Comment by pipixia244** [comment]
多卡不符合绝大多数人的使用场景，不会提供多卡支持以及更大的模型。

可以自行使用其他工具。
