### ISSUE TITLE
[Bug] 关于wiki里提到的python部署教程中的translate_epub.py中的gpt_dict_path参数

### ISSUE THREAD

**Issue by wingwwww** [SakuraLLM/SakuraLLM#111]
**描述一下Bug**
源代码里有个gpt_dict_path参数默认是None，因为没打算额外使用词典，所以没管，但会导致下面的open报错（不能打开None type），想请教一下如果不使用词典的应该将它改成什么好，以及有没有考虑过更换默认值，希望大佬能解答一下，十分感谢

**截图**
源代码：
`def extra_args(parser: ArgumentParser):
        epub_group = parser.add_argument_group("Epub")
        epub_group.add_argument("--data_path", type=str, default="", help="file path of the epub you want to translate.")
        epub_group.add_argument("--data_folder", type=str, default="", help="folder path of the epubs you want to translate.")
        epub_group.add_argument("--output_folder", type=str, default="", help="save folder path of the epubs model translated.")
        epub_group.add_argument("--text_length", type=int, default=512, help="input max length in each inference.")
        epub_group.add_argument("--translate_title", action='store_true', help='whether to translate the file names of the epubs')
        epub_group.add_argument("--gpt_dict_path", type=str, default=None, help="whether to use glossary dict to translate.")
    args = utils.cli.parse_args(do_validation=True, add_extra_args_fn=extra_args)
    import coloredlogs
    coloredlogs.install(level="INFO")
    with open(args.gpt_dict_path, 'r', encoding='utf-8') as f:`

报错
`    with open(args.gpt_dict_path, 'r', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None'
`

**Comment by kurikomoe** [comment]
我修一下，审代码的时候没注意这一点

**Comment by wingwwww** [comment]
好的，感谢回答
