### ISSUE TITLE
[Bug] GalTransl-7B-v2重复输出

### ISSUE THREAD

**Issue by Moon-404** [SakuraLLM/SakuraLLM#114]
**描述一下Bug**
例如“無理無理無理無理”的输出可能会是“不行不行不行不行不行不行不行……”，即重复输出的语气词的次数超过了原文的次数。

**版本与参数（重要）**
 - OS: Win 11
 - Python版本 3.10
 - 是否使用GPU，使用什么GPU. 4070 Ti Super
 - 你使用的llama.cpp/llama-cpp-python/autogptq/transformers库的版本 llama-cpp-python latest
 - 你使用的模型版本 GalTransl-7B-v2
 - 如果是模型输出问题，请同时附上模型的解码参数 默认

**Comment by Moon-404** [comment]
默认参数里面 `frequency_penalty` 是 0 还是 0.2？我之后手动设定一下看看有没有好转。

**Comment by sakura-umi** [comment]
如果遇到退化，可以尝试将`frequency_penalty`设置成0.2甚至更高，但如果没有退化的话建议还是为0.
