### ISSUE TITLE
Kaggle已禁SakuraLLM，請移除教程

### ISSUE THREAD

**Issue by cycham0** [SakuraLLM/SakuraLLM#115]
Thank you for your inquiry. We have unblocked your "{id_name}" Kaggle account. The account was locked as there was SakuraLLM used in your account. **Please avoid SakuraLLM on Kaggle platform as it is prohibited on Kaggle platform.** This will lead to permanent ban. The account will not be reinstated if the account gets blocked again.

**Comment by kurikomoe** [comment]
Sure
