### ISSUE TITLE
[Feature Request]希望后续训练考虑加强控制符例如换行符之类的训练

### ISSUE THREAD

**Issue by RoadToNowhereX** [SakuraLLM/SakuraLLM#41]
目前0.9版本模型在处理galgame文本中的控制符时显得比较智障，会出现无限循环输出单个控制符，直接吞掉句子中的换行符等问题，即使是在prompt中强调也依然会反复出现。希望在后续版本中针对控制符加强训练，减少此类问题出现

**Comment by pipixia244** [comment]
1. 控制符可否提供几个例子？无法在前端检测到并单独处理吗？目前模型的任务定义**不包括非纯文本的内容**。
2. 在模型使用多样性的instruct训练之前，请不要随意修改prompt。后面会增强模型指令遵循的能力。

**Comment by RoadToNowhereX** [comment]
> 1. 控制符可否提供几个例子？无法在前端检测到并单独处理吗？目前模型的任务定义**不包括非纯文本的内容**。
> 2. 在模型使用多样性的instruct训练之前，请不要随意修改prompt。后面会增强模型指令遵循的能力。

比如\n, \r\n, \\, <r>, %p
可以在前端处理掉，但是内嵌在句中的换行符会丢失位置，还有某些单独成句的控制符在删去后也很难复原在原来哪一行

**Comment by RoadToNowhereX** [comment]
> 1. 控制符可否提供几个例子？无法在前端检测到并单独处理吗？目前模型的任务定义**不包括非纯文本的内容**。
> 2. 在模型使用多样性的instruct训练之前，请不要随意修改prompt。后面会增强模型指令遵循的能力。

居然是妮可校友，吃惊

**Comment by pipixia244** [comment]
> > 1. 控制符可否提供几个例子？无法在前端检测到并单独处理吗？目前模型的任务定义**不包括非纯文本的内容**。
> > 2. 在模型使用多样性的instruct训练之前，请不要随意修改prompt。后面会增强模型指令遵循的能力。
> 
> 比如\n, \r\n, \, , %p 可以在前端处理掉，但是内嵌在句中的换行符会丢失位置，还有某些单独成句的控制符在删去后也很难复原在原来哪一行

所以要翻译的句子大概长成这个样子：
xxxxxxx \r\n xxxxxx
xxxxxxxxxxxxxxxxxx
xxxxxx \n xxxxxxxx 
我理解的对吗？就是既有真正的换行 也有行内的“换行”？

**Comment by RoadToNowhereX** [comment]
> > > 1. 控制符可否提供几个例子？无法在前端检测到并单独处理吗？目前模型的任务定义**不包括非纯文本的内容**。
> > > 2. 在模型使用多样性的instruct训练之前，请不要随意修改prompt。后面会增强模型指令遵循的能力。
> > 
> > 
> > 比如\n, \r\n, , , %p 可以在前端处理掉，但是内嵌在句中的换行符会丢失位置，还有某些单独成句的控制符在删去后也很难复原在原来哪一行
> 
> 所以要翻译的句子大概长成这个样子： xxxxxxx \r\n xxxxxx xxxxxxxxxxxxxxxxxx xxxxxx \n xxxxxxxx 我理解的对吗？就是既有真正的换行 也有行内的“换行”？

对的，竹子社一些游戏就是把换行符\n以纯文本形式内嵌，escude的提出来也发现文本中间有<r>

**Comment by fkiliver** [comment]
我是以换行符这类符号为分割，分段提交给模型翻译后再合并的，你可以试试

**Comment by kurikomoe** [comment]
> > > > 1. 控制符可否提供几个例子？无法在前端检测到并单独处理吗？目前模型的任务定义**不包括非纯文本的内容**。
> > > > 2. 在模型使用多样性的instruct训练之前，请不要随意修改prompt。后面会增强模型指令遵循的能力。
> > > 
> > > 
> > > 比如\n, \r\n, , , %p 可以在前端处理掉，但是内嵌在句中的换行符会丢失位置，还有某些单独成句的控制符在删去后也很难复原在原来哪一行
> > 
> > 
> > 所以要翻译的句子大概长成这个样子： xxxxxxx \r\n xxxxxx xxxxxxxxxxxxxxxxxx xxxxxx \n xxxxxxxx 我理解的对吗？就是既有真正的换行 也有行内的“换行”？
> 
> 对的，竹子社一些游戏就是把换行符\n以纯文本形式内嵌，escude的提出来也发现文本中间有<'r>

这种手动控制文本换行的游戏，你也只能先去掉换行符，之后翻译出来，再加回去。
从效果上考量，由于翻译后的文本长短不一样，就算按原位置放换行符也可能出现游戏内文本行过长的现象。

这种游戏的汉化咱建议是让汉化组的程序写代码处理，计算一行内文本实际像素宽度来加换行符。
（当然 AC 那边懒省事，直接在校对阶段用 excel 表格的宽度来手动加换行符，也是一种办法。

**Comment by sakura-umi** [comment]
最新发布的的[1.0版本模型](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0pre1-GGUF)换行符的保持可能有一定提升。
