### ISSUE TITLE
[Bug] Model error

### ISSUE THREAD

**Issue by paul0728** [SakuraLLM/SakuraLLM#80]
1.無法使用sakura-32b-qwen2beta-v0.10pre1-q4km.gguf
error message : unknown model architecture: 'qwen2'
![螢幕擷取畫面 2024-05-15 193205](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/44644609/6738f5a6-aa2c-494f-b0b9-87751562218a)

2.[Sakura-14B-Qwen2beta-v0.10pre0-GGUF](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2beta-v0.10pre0-GGUF) 連結失效([鏡像網站](https://hf-mirror.com/SakuraLLM/Sakura-14B-Qwen2beta-v0.10pre0-GGUF)也失效)

**Comment by kurikomoe** [comment]
https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/71#issuecomment-2067939342

**Comment by pipixia244** [comment]
> > [#71 (comment)](https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/71#issuecomment-2067939342)
> 
> 謝謝你,雖然可以運行,但是使用上仍然有問題 ![image](https://private-user-images.githubusercontent.com/44644609/330815261-704676ae-5715-490f-8f27-8da761a9b8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4OTcsIm5iZiI6MTcxNTgyMzU5NywicGF0aCI6Ii80NDY0NDYwOS8zMzA4MTUyNjEtNzA0Njc2YWUtNTcxNS00OTBmLThmMjctOGRhNzYxYTliOGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAxMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTRmMDE1ZjI0NzdhMTgzN2RlNjA4NzA2MDZhMGU3YmFkN2ViZjVlY2YyM2ZiY2JmZmU2OTZkZWQzMTAxYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W05_KHes4CcoP564gE81eBNvc7PEMwFq4_eoZvI9WOI)

启动命令有问题，没有正确指定模型版本。

**Comment by paul0728** [comment]
> > > [#71 (comment)](https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/71#issuecomment-2067939342)
> > 
> > 
> > 謝謝你,雖然可以運行,但是使用上仍然有問題 ![image](https://private-user-images.githubusercontent.com/44644609/330815261-704676ae-5715-490f-8f27-8da761a9b8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4OTcsIm5iZiI6MTcxNTgyMzU5NywicGF0aCI6Ii80NDY0NDYwOS8zMzA4MTUyNjEtNzA0Njc2YWUtNTcxNS00OTBmLThmMjctOGRhNzYxYTliOGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAxMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTRmMDE1ZjI0NzdhMTgzN2RlNjA4NzA2MDZhMGU3YmFkN2ViZjVlY2YyM2ZiY2JmZmU2OTZkZWQzMTAxYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W05_KHes4CcoP564gE81eBNvc7PEMwFq4_eoZvI9WOI)
> 
> 启动命令有问题，没有正确指定模型版本。

我的指令是這樣下的,請問有錯嗎?
python server.py --model_name_or_path C:\translator\text-generation-webui\models\sakura-32b-qwen2beta-v0.10pre1-q4km.gguf --llama_cpp --use_gpu --model_version 0.10 --trust_remote_code --no-auth

**Comment by pipixia244** [comment]
> > > > [#71 (comment)](https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/71#issuecomment-2067939342)
> > > 
> > > 
> > > 謝謝你,雖然可以運行,但是使用上仍然有問題 ![image](https://private-user-images.githubusercontent.com/44644609/330815261-704676ae-5715-490f-8f27-8da761a9b8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4OTcsIm5iZiI6MTcxNTgyMzU5NywicGF0aCI6Ii80NDY0NDYwOS8zMzA4MTUyNjEtNzA0Njc2YWUtNTcxNS00OTBmLThmMjctOGRhNzYxYTliOGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAxMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTRmMDE1ZjI0NzdhMTgzN2RlNjA4NzA2MDZhMGU3YmFkN2ViZjVlY2YyM2ZiY2JmZmU2OTZkZWQzMTAxYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W05_KHes4CcoP564gE81eBNvc7PEMwFq4_eoZvI9WOI)
> > 
> > 
> > 启动命令有问题，没有正确指定模型版本。
> 
> 我的指令是這樣下的,請問有錯嗎? python server.py --model_name_or_path C:\translator\text-generation-webui\models\sakura-32b-qwen2beta-v0.10pre1-q4km.gguf --llama_cpp --use_gpu --model_version 0.10 --trust_remote_code --no-auth

是否pull了最新的代码？

**Comment by paul0728** [comment]
> > > > > [#71 (comment)](https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/71#issuecomment-2067939342)
> > > > 
> > > > 
> > > > 謝謝你,雖然可以運行,但是使用上仍然有問題 ![image](https://private-user-images.githubusercontent.com/44644609/330815261-704676ae-5715-490f-8f27-8da761a9b8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4OTcsIm5iZiI6MTcxNTgyMzU5NywicGF0aCI6Ii80NDY0NDYwOS8zMzA4MTUyNjEtNzA0Njc2YWUtNTcxNS00OTBmLThmMjctOGRhNzYxYTliOGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAxMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTRmMDE1ZjI0NzdhMTgzN2RlNjA4NzA2MDZhMGU3YmFkN2ViZjVlY2YyM2ZiY2JmZmU2OTZkZWQzMTAxYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W05_KHes4CcoP564gE81eBNvc7PEMwFq4_eoZvI9WOI)
> > > 
> > > 
> > > 启动命令有问题，没有正确指定模型版本。
> > 
> > 
> > 我的指令是這樣下的,請問有錯嗎? python server.py --model_name_or_path C:\translator\text-generation-webui\models\sakura-32b-qwen2beta-v0.10pre1-q4km.gguf --llama_cpp --use_gpu --model_version 0.10 --trust_remote_code --no-auth
> 
> 是否pull了最新的代码？

昨天有先PULL喔
還是有沒有可能是硬體設備問題?RAM 或是VRAM OOM之類的?

**Comment by pipixia244** [comment]
确认使用了最新的代码后，麻烦执行一下tests/example_openai.py，然后发一下完整的运行结果截图。

**Comment by paul0728** [comment]
執行tests/example_openai.py的結果
![螢幕擷取畫面 2024-05-22 140447](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/44644609/961fa25b-d8a5-4b2d-83fe-8c59ccb18b0b)

**Comment by pipixia244** [comment]
需要在运行server的同时运行example_openai.py
