### ISSUE TITLE
大佬，qwen2发布了，请问有计划更新7B以下的小模型吗？

### ISSUE THREAD

**Issue by solaers** [SakuraLLM/SakuraLLM#90]
如题。大佬，qwen2最近发布了，7B、1.5B和0.5B的小模型性能提升挺大的，请问有计划更新一下小模型吗？

**Comment by CberYellowstone** [comment]
附议

**Comment by lingyezhixing** [comment]
+1

**Comment by lingyezhixing** [comment]
附议

**Comment by lingyezhixing** [comment]
> 如题。大佬，qwen2最近发布了，7B、1.5B和0.5B的小模型性能提升挺大的，请问有计划更新一下小模型吗？

（以下测试结果仅供参考）使用Qwen2-7B-Instruct-Q4_K_M，启用“--flash-attn”，可以一次性逐句翻译近万字的小说文本且能够正确处理所有换行，没有出现前两代听不懂指令的情况，有理由认为Qwen2-7B-Instruct相比于Qwen1.5-&B-Chat和Qwen-7B-Chat在文本处理相关的指令响应准确率上有着极大的提升，所以微调为翻译模型应该也会有很大的性能提升。考虑到目前官方还没有发布14B规格的模型，如果要用Qwen2进行微调，目前Qwen2-7B应该是Qwen2系列里最合适的选择。

**Comment by pipixia244** [comment]
没有理由不跟进最新的
只是需要时间

**Comment by sakura-umi** [comment]
基于qwen2.5-14b的[模型](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0pre1-GGUF)已经发布，7b以及更小的模型在准备和进行中。
