### ISSUE TITLE
error loading model: unknown model architecture: ‘qwen2‘

### ISSUE THREAD

**Issue by huaihkiss** [SakuraLLM/SakuraLLM#92]
llama_cpp_python不支持qwen2，需要更新，需要按照cuda版本更新，如果没有按照cuda版本更新可能会不使用显卡

`
#卸载原有
pip uninstall llama-cpp-python
#安装新版，cuda-version为cu121、cu122、cu123、cu124，python版本仅支持3.10、3.11、3.12
pip install llama-cpp-python \
  --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/<cuda-version>
 
#假设为cuda 12.1
 
pip install llama-cpp-python \
  --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121
`

**Comment by kurikomoe** [comment]
updated in `usage.md`
