### ISSUE TITLE
[Feature] ADD Subtitle support

### ISSUE THREAD

**Issue by ywtse** [SakuraLLM/SakuraLLM#94]
modified "translate_novel.py" to support subtitle [srt/ass]
requirements:
pip install -U pysubs2 opencc

[translate_subtitle.zip](https://github.com/user-attachments/files/15856292/translate_subtitle.zip)

both files need to save under Sakura-13B-Galgame folder

result [ass] will contain translated on top of the original japanese subtitle with smaller font size.
since my TV doesn't support [ass], i have include "ass2srt_remove_original.py" to keep only the translated subtitle as [srt]

option "--save_traditional" to save as Traditional Chinese if need.

**Comment by kurikomoe** [comment]
Thanks for your work! Would you consider turning this into a PR?
If possible, ass/srt related things could be moved into a new Python script `translate_sub.py`.

**Comment by ywtse** [comment]
Hi kurikomoe,
if you found the code is good enough, you're free to merge it to PR.

**Comment by ywtse** [comment]
ref https://github.com/SakuraLLM/SakuraLLM/pull/95

Closed
