### ISSUE TITLE
[Feature Request] 纠结模型效果

### ISSUE THREAD

**Issue by yihuishou** [SakuraLLM/SakuraLLM#97]
想知道在 24G显卡上
GalTransl-7B-v1.5-Q6_K 和 Sakura-32b-qwen2beta-v0.10pre1-q4km、Sakura-14b-qwen2beta-v0.9.2-q6k
哪个翻译游戏效果最好？
14b Q6_K 和 32b Q4KM 很纠结

**Comment by pipixia244** [comment]
如果是14b和32b之间选择的话，目前的情况下先用14b的Sakura-14b-qwen2beta-v0.9.2-q6k吧
如果想要更快的速度和术语表的话，也可以用galtransl-7b
