### ISSUE TITLE
[Feature Request] 关于 AMD 显卡 集成 ZLUDA 是否能加快翻译速度？

### ISSUE THREAD

**Issue by yihuishou** [SakuraLLM/SakuraLLM#98]
RT.

**Comment by pipixia244** [comment]
加速方法与模型本身无关，非模型侧的功能。
同时开发者并没有AMD显卡用于测试，请于[llama.cpp](https://github.com/ggerganov/llama.cpp/issues)仓库或其他相关推理框架仓库进行提问。
